from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "191282743bea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_index(
        op.f("ix__users__phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_table(
        "telegram_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("picture", sa.String(length=1024), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__telegram_accounts__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__telegram_accounts")),
    )
    op.create_index(
        op.f("ix__telegram_accounts__telegram_id"),
        "telegram_accounts",
        ["telegram_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix__telegram_accounts__user_id"),
        "telegram_accounts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__telegram_accounts__user_id"), table_name="telegram_accounts"
    )
    op.drop_index(
        op.f("ix__telegram_accounts__telegram_id"), table_name="telegram_accounts"
    )
    op.drop_table("telegram_accounts")
    op.drop_index(op.f("ix__users__phone_number"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
